### PR TITLE
Layouts & Sidebar & Optimizations & Code Rebase & More

### PR DESCRIPTION
**Pull request by ozturkkl**
This is a huge update simply because the layout functionality hits every aspect of the system. I suggest other devs to skim over the changes at [here](https://github.com/Razorwind1/Custom-Links-Project/compare/master...kl_layouts#files_bucket) to review the code and get an understanding of the changes.

If you discover any bugs or have suggestions for improvements, kindly note them here so that we can go over them when we meet.

Please let me know if you have any questions about any change or the functionality overall.

### CODE REVIEW

**Comment by ozturkkl** [comment]
Also, there were no big conflicts except TagList.vue, I accepted all the incoming changes but still wasn't able to get it working. I think we need to go over it together and see what I'm missing @Razorwind1

**Comment by Razorwind1** [comment]
Wow, looks good! So many files changed!

We can review TagsList.vue today. If it's easier to just do the merge and then set a task to fix the TagsList.vue I'm cool with that too - it would just be really nice to be able to have these updates in master soon.

**Review by Razorwind1 — APPROVED** [review]

**Review by ozturkkl — COMMENTED** [review]
Reviewed all changes before final merge. There is a bug that needs to be addressed with Edit Add Link popup. BUG: When editing a link with a custom img, the custom img does not show up.

**Comment by ozturkkl** [comment]
Finally fixed the bug after almost giving up on it. Now merging.

**Pull request merged**
